// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqcsq_dTM-MAEZine-E6kuT1fzCbegY8E',
    appId: '1:405952516189:web:0e9d2e90108156ff2efdb4',
    messagingSenderId: '405952516189',
    projectId: 'mysterious-santa',
    authDomain: 'mysterious-santa.firebaseapp.com',
    storageBucket: 'mysterious-santa.firebasestorage.app',
    measurementId: 'G-L6BL49R4W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-6ynsQCDgJTTpWqKXpLCrFV6j-vZga8I',
    appId: '1:405952516189:android:b07c451d77fc47662efdb4',
    messagingSenderId: '405952516189',
    projectId: 'mysterious-santa',
    storageBucket: 'mysterious-santa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3nGjD5CUSFb4mxlT1LaYh1xEROzohJT4',
    appId: '1:405952516189:ios:07c2c48cf6b48a952efdb4',
    messagingSenderId: '405952516189',
    projectId: 'mysterious-santa',
    storageBucket: 'mysterious-santa.firebasestorage.app',
    iosBundleId: 'news.afisha.mysterioussanta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3nGjD5CUSFb4mxlT1LaYh1xEROzohJT4',
    appId: '1:405952516189:ios:07c2c48cf6b48a952efdb4',
    messagingSenderId: '405952516189',
    projectId: 'mysterious-santa',
    storageBucket: 'mysterious-santa.firebasestorage.app',
    iosBundleId: 'news.afisha.mysterioussanta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqcsq_dTM-MAEZine-E6kuT1fzCbegY8E',
    appId: '1:405952516189:web:8939d97ba98796e22efdb4',
    messagingSenderId: '405952516189',
    projectId: 'mysterious-santa',
    authDomain: 'mysterious-santa.firebaseapp.com',
    storageBucket: 'mysterious-santa.firebasestorage.app',
    measurementId: 'G-WHTVMP1GCY',
  );
}
